### ISSUE TITLE
Possibly implement setting root directory for non-LSP projects

### ISSUE THREAD

**Issue by famiu** [ahmedkhalf/lsp-rooter.nvim#2]
The title should be pretty self-explanatory. I think it'd be neat for this plugin to be able to set the root directory even without LSP (when LSP isn't available) through detecting certain patterns like the `.git` directory, or even things like looking for a `Cargo.toml` file, etc. which would be configurable by the user, sort of like [`vim-rooter`](https://github.com/airblade/vim-rooter). Because I personally use some projects without LSP, but I'd also like the LSP integration which this plugin provides.

**Comment by pidgeon777** [comment]
Would it be possible to do something like this?:

root_pattern = C:\path\to\root\

And when some buffers are activated:

buff1_p = **C:\path\to\root**\file
buff2_p = **C:\path\to\root**\dir\file
buff3_p = C:\path\to\another\file

then `buff1_p` and `buff2_p` get *cd'ed* to `root_pattern`, when activated/focused.

Note: the ability to assign multiple root patterns should be given (`root_path1`, `root_path2`...), even better with *regex* support.

**Comment by famiu** [comment]
I'd say do it like how [`vim-rooter`](https://github.com/airblade/vim-rooter) does it.

**Comment by pidgeon777** [comment]
> I'd say do it like how [`vim-rooter`](https://github.com/airblade/vim-rooter) does it.

Does it support multiple roots based on path patterns + regex?

Consider the example I posted in my previous message.

**Comment by famiu** [comment]
> > I'd say do it like how [`vim-rooter`](https://github.com/airblade/vim-rooter) does it.
> 
> Does it support multiple roots based on path patterns + regex?
> 
> Consider the example I posted in my previous message.

Yes, and it supports a lot more

**Comment by pidgeon777** [comment]
Very interesting. I'll try it right now!

**Comment by ahmedkhalf** [comment]
Since this plugin is mainly lsp based: what do you think that instead of re-implementing already existing functionality into something that doesn't quite fit, I add a callback function that executes whenever `lsp-rooter` fails to detect an lsp project directory, and inside of this callback function you can add whichever behavior you desire including using `vim-rooter` itself.

**Comment by pidgeon777** [comment]
It could be a nice idea, even if a complete LUA plugin integrating more functionalities would be cool.

Moreover, according to some reports `vim-rooter` doesn't seem to properly work in Windows 10.

Let see what the others think, though.

**Comment by gegoune** [comment]
I also would like to see that functionality. I want to disable couple of LSPs and set root based on existence of `.git` in my use case. I am not sure if having another plugin running at the same time is a good idea, wouldn't they be in each others way?

**Comment by ram02z** [comment]
> I am not sure if having another plugin running at the same time is a good idea, wouldn't they be in each others way?

Not necessarily. You can set vim-rooter to manual mode and have it run only in the callback function.

**Comment by ahmedkhalf** [comment]
DONE!

However, it's in another repo:
Please use [project.nvim](https://github.com/ahmedkhalf/project.nvim).

@pwntester @eddyekofo94 @bhavitsharma @dm19 @lucax88x @pidgeon777 @kuator @jonz94 @lourenci @UltiRequiem @famiu @ram02z @gegoune
