### ISSUE TITLE
Ability to ignore a certain LSP servers

### ISSUE THREAD

**Issue by chaitanyabsprip** [ahmedkhalf/lsp-rooter.nvim#3]
I am using efm alongside most of my LSP servers and efm kind of messes with my root directory, so I would like if there is a way to exclude a few LSP servers, in myy case, efm.

**Comment by ahmedkhalf** [comment]
You can now use this:
```lua
require('lsp-rooter').setup {
  ignore_lsp = {"efm"},
}
```
where `ignore_lsp` is a table of lsp clients to ignore by name.
Please let me know if this works for you.

**Comment by chaitanyabsprip** [comment]
this works fine now. Thank you for your help!
